stages:
  - 👷 build
  - 🚀 deploy

build:
  stage: 👷 build
  image:
    name: sglahn/platformio-core
    entrypoint: [""]
  before_script:
    - pio --version
    - pio init
  script:
    - pio run -e sanguino_atmega1284p
  artifacts:
    paths:
      - .pioenvs/sanguino_atmega1284p/firmware.hex

USB flash 🔌:
  stage: 🚀 deploy
  tags:
    - lweber-laptop
  when: manual
  image:
    name: akshmakov/avrdude
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  script:
    - avrdude -p m1284p -c stk500v1 -P /dev/ttyUSB0 -b 57600 -U flash:w:.pioenvs/sanguino_atmega1284p/firmware.hex:i

OTA flash 📶:
  stage: 🚀 deploy
  image: docker
  when: manual
  tags:
    - lweber-runner
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: tcp://${RPI_HOST}:2375
  before_script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "${SSH_PRIVATE_KEY_B64}" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - scp $(pwd)/.pioenvs/sanguino_atmega1284p/firmware.hex ${SSH_USER}@${RPI_HOST}:/tmp/firmware.hex
    - docker container stop octoprint
  script:
    - docker run --rm --privileged -v /tmp/firmware.hex:/tmp/firmware.hex:ro akshmakov/avrdude:arm32v7 -p m1284p -c stk500v1 -P /dev/ttyUSB0 -b 57600 -U flash:w:/tmp/firmware.hex:i
  after_script:
    - docker container start octoprint